'use client'

import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function ProfileSetupPage() {
  const router = useRouter(); const search = useSearchParams(); const next = search.get('next') || '/home'
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [avatar,setAvatar]=useState<File|null>(null)
  const [form,setForm]=useState({display_name:'',username:'',bio:'',country:'Sierra Leone',region:'',district:'',chiefdom:'',occupation:'',preferred_language:'en'})
  useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace('/auth');return}if(!user.email_confirmed_at){router.replace('/auth');return}const {data:profile}=await s.from('profiles').select('*').eq('id',user.id).maybeSingle();setForm(v=>({...v,display_name:profile?.display_name||user.user_metadata?.display_name||'',country:profile?.country||'Sierra Leone',region:profile?.region||user.user_metadata?.region||'',district:profile?.district||user.user_metadata?.district||'',chiefdom:profile?.chiefdom||user.user_metadata?.chiefdom||'',occupation:profile?.occupation||user.user_metadata?.occupation||'',preferred_language:profile?.preferred_language||'en',username:profile?.username||'',bio:profile?.bio||''}));setLoading(false)})()},[router])
  function set(k:keyof typeof form,v:string){setForm(f=>({...f,[k]:v}))}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace('/auth');return}let avatar_url:string|undefined
    if(avatar){const ext=avatar.name.split('.').pop()||'jpg';const path=`${user.id}/avatar-${crypto.randomUUID()}.${ext}`;const up=await s.storage.from('slorigins-media').upload(path,avatar,{upsert:false,contentType:avatar.type});if(up.error){setSaving(false);setMessage(up.error.message);return}avatar_url=s.storage.from('slorigins-media').getPublicUrl(path).data.publicUrl}
    const payload={id:user.id,...form,role:user.user_metadata?.role||'member',verification_status:'verified',onboarding_step:3,onboarding_complete:true,email_verified:true,...(avatar_url?{avatar_url}:{})};const {error}=await s.from('profiles').upsert(payload);setSaving(false);if(error){setMessage(error.message);return}router.replace(next);router.refresh()}
  if(loading)return <main className="mx-auto max-w-3xl px-5 py-20 text-sm text-neutral-500">Loading your profile…</main>
  return <main className="mx-auto max-w-3xl px-5 py-12 lg:px-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-500">Profile setup</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">One last step before your community home</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-500">Your email is verified. Add the public details people will use to understand who you are and what you do.</p><form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm font-medium">Profile photo<span className="text-xs font-normal text-neutral-500">Required. JPG, PNG or WebP.</span><input type="file" accept="image/jpeg,image/png,image/webp" required onChange={(e:ChangeEvent<HTMLInputElement>)=>setAvatar(e.target.files?.[0]||null)} className="rounded-lg border border-neutral-200 px-3 py-3 text-sm"/></label><div className="grid gap-5 sm:grid-cols-2">{[['display_name','Name'],['username','Username'],['occupation','What you do'],['region','Region / province'],['district','District'],['chiefdom','Chiefdom / town']].map(([k,label])=><label key={k} className="grid gap-2 text-sm font-medium">{label}<input required value={form[k as keyof typeof form]} onChange={e=>set(k as keyof typeof form,e.target.value)} className="border-b border-neutral-300 bg-transparent px-0 py-3 outline-none focus:border-neutral-900"/></label>)}</div><label className="grid gap-2 text-sm font-medium">Short bio<textarea rows={4} value={form.bio} onChange={e=>set('bio',e.target.value)} className="rounded-lg border border-neutral-200 px-3 py-3 outline-none focus:border-neutral-900" placeholder="Tell the community what you make, study, source or care about."/></label><label className="grid gap-2 text-sm font-medium">Preferred language<select value={form.preferred_language} onChange={e=>set('preferred_language',e.target.value)} className="rounded-lg border border-neutral-200 bg-white px-3 py-3 outline-none"><option value="en">English</option><option value="kri">Krio</option><option value="men">Mende</option><option value="tem">Temne</option></select></label>{message&&<p className="text-sm text-red-700">{message}</p>}<button disabled={saving||!avatar} className="w-fit rounded-lg bg-neutral-900 px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{saving?'Saving…':'Open community home'}</button></form></main>
}
