import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, CheckCircle2, MapPinned, ShieldCheck, Users, FileCheck2, ArrowRight } from 'lucide-react'
const data:Record<string,{name:string;region:string;category:string;summary:string;image:string;facts:string[]}>={
 'cocoa-fine-cacao':{name:'Cocoa & fine cacao',region:'Eastern Province',category:'Agriculture',summary:'A discovery page for Sierra Leonean cacao supply, story and value-add opportunities.',image:'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=1600&q=85',facts:['Community supply signal','Origin documentation path','Quality and sampling workflow','International sourcing enquiry']},
 'natural-fibres':{name:'Natural fibres',region:'Northern Province',category:'Materials',summary:'Explore local fibre traditions, makers, possible applications and responsible sourcing routes.',image:'https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=1600&q=85',facts:['Local maker stories','Material specification','Responsible sourcing review','Buyer sampling workflow']},
 'palm-craftwork':{name:'Palm-derived craftwork',region:'Southern Province',category:'Craft & culture',summary:'Community-made pieces and material stories presented for discovery, not mass-market commoditisation.',image:'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=1600&q=85',facts:['Maker attribution','Cultural context','Small-batch availability','Buyer enquiry path']},
 'coffee-highlands':{name:'Highland coffee',region:'Eastern Province',category:'Agriculture',summary:'A sourcing story for specialty coffee opportunities and smallholder value addition.',image:'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1600&q=85',facts:['Producer profile','Sample request','Quality notes','Export-readiness review']},
 'clay-ceramics':{name:'Natural clay & ceramics',region:'Western Area',category:'Materials',summary:'Discover locally crafted ceramics, clay stories and small-batch design collaborations.',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=1600&q=85',facts:['Maker attribution','Material origin','Small-batch catalogue','Buyer collaboration']},
 'spice-gardens':{name:'Aromatic spice crops',region:'Northern Province',category:'Agriculture',summary:'Explore aromatic crops, producer stories and opportunities for responsible ingredient sourcing.',image:'https://images.unsplash.com/photo-1509351631168-9b7d2ef0a7c9?auto=format&fit=crop&w=1600&q=85',facts:['Producer story','Harvest season','Sample enquiry','Compliance review']}}
export default async function Detail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=data[slug];if(!d)notFound();return <section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><Link href="/discover" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-sky-700"><ArrowLeft size={16}/> Back to discover</Link><div className="overflow-hidden rounded-[2.2rem] border border-sky-100 bg-white shadow-[0_24px_80px_rgba(15,84,110,.09)]"><div className="grid lg:grid-cols-2"><div className="min-h-[360px] overflow-hidden bg-sky-50"><img src={d.image} alt="" className="h-full w-full object-cover"/></div><div className="p-7 md:p-10"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">{d.category}</span><span className="inline-flex items-center gap-1 rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold text-slate-500"><MapPinned size={13}/>{d.region}</span></div><h1 className="mt-5 text-4xl font-black tracking-tight md:text-5xl">{d.name}</h1><p className="mt-4 text-base leading-7 text-slate-600">{d.summary}</p><div className="mt-7 grid gap-3">{d.facts.map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-slate-50 px-4 py-3 text-sm font-semibold"><CheckCircle2 className="text-emerald-500" size={18}/>{x}</div>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Link href="/buyers/new-request" className="rounded-2xl bg-sky-600 px-5 py-3 text-center text-sm font-bold text-white">Request sourcing</Link><Link href="/source" className="rounded-2xl border border-sky-200 px-5 py-3 text-center text-sm font-bold text-sky-700">Add evidence</Link></div></div></div></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><Panel icon={ShieldCheck} title="Verification" text="Community evidence, origin details and compliance checks are kept visible in the sourcing trail." href="/verification"/><Panel icon={Users} title="Community" text="See contributor context, maker stories and local notes connected to this discovery." href="/community"/><Panel icon={FileCheck2} title="Export readiness" text="Read the journey from discovery to a compliant sourcing conversation." href="/how-it-works"/></div></section>}
function Panel({icon:Icon,title,text,href}:{icon:any;title:string;text:string;href:string}){return <Link href={href} className="rounded-[1.5rem] border border-sky-100 bg-white p-6 shadow-sm hover:-translate-y-0.5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-600"><Icon size={20}/></div><h2 className="mt-4 font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-sky-700">Open <ArrowRight size={14}/></span></Link>}