import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

export default async function HomePage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return <main className="mx-auto max-w-4xl px-5 py-20"><h1 className="text-2xl font-semibold">Your community home</h1><p className="mt-2 text-sm leading-6 text-neutral-500">Sign in to open your community feed.</p><Link href="/auth?next=/home" className="mt-5 inline-block rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">Sign in</Link></main>
  const { data: profile } = await supabase.from('profiles').select('*').eq('id', user.id).maybeSingle()
  if (!profile?.onboarding_complete || !profile.avatar_url) return <main className="mx-auto max-w-3xl px-5 py-20"><h1 className="text-2xl font-semibold">Complete your profile</h1><p className="mt-2 text-sm leading-6 text-neutral-500">Your community home opens after your verified profile is complete.</p><Link href="/profile/setup?next=/home" className="mt-5 inline-block rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white">Finish profile</Link></main>
  const { data: posts } = await supabase.from('community_posts').select('id, body, image_url, created_at, author_id').order('created_at', { ascending: false }).limit(30)
  const authorIds = [...new Set((posts||[]).map(p=>p.author_id))]
  const { data: authors } = authorIds.length ? await supabase.from('profiles').select('id, display_name, username, avatar_url, occupation, region').in('id', authorIds) : { data: [] }
  const authorMap = new Map((authors||[]).map(a=>[a.id,a]))
  return <main className="mx-auto max-w-5xl px-5 py-8 lg:px-8"><div className="flex items-center justify-between gap-4 border-b border-neutral-200 pb-5"><div><p className="text-xs text-neutral-500">Welcome back</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Community home</h1><p className="mt-1 text-sm text-neutral-500">{profile.display_name || user.email}</p></div><Link href="/post/new" className="rounded-lg bg-neutral-900 px-4 py-2.5 text-sm font-semibold text-white">Create post</Link></div><div className="mt-7 grid gap-8 lg:grid-cols-[1fr_280px]"><section><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-semibold">Latest from the community</h2><Link href="/community" className="text-xs font-medium text-neutral-500 hover:text-neutral-900">Browse all</Link></div><div className="grid gap-5">{(posts||[]).length===0?<div className="border-y border-neutral-200 py-10 text-sm text-neutral-500">No posts yet. Be the first to share a note, image or discovery.</div>:(posts||[]).map(post=>{const a=authorMap.get(post.author_id);return <article key={post.id} className="border-b border-neutral-200 pb-6"><div className="flex items-center gap-3"><img src={a?.avatar_url||'/images/avatar-placeholder.svg'} alt="" className="h-9 w-9 rounded-full object-cover bg-neutral-100"/><div><Link href={`/profile/${a?.username||post.author_id}`} className="text-sm font-semibold hover:underline">{a?.display_name||'Community member'}</Link><p className="text-xs text-neutral-500">{a?.occupation||'Community' }{a?.region?` · ${a.region}`:''}</p></div></div>{post.body&&<p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-neutral-800">{post.body}</p>}{post.image_url&&<img src={post.image_url} alt="Community post" className="mt-4 max-h-[520px] w-full rounded-xl object-cover"/>}</article>})}</div></section><aside className="h-fit border-l border-neutral-200 pl-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-neutral-400">Your space</p><nav className="mt-4 grid gap-1 text-sm"><Link href="/profile" className="py-2 hover:text-neutral-500">Profile</Link><Link href="/post/new" className="py-2 hover:text-neutral-500">Create a post</Link><Link href="/discover" className="py-2 hover:text-neutral-500">Discover</Link><Link href="/regions" className="py-2 hover:text-neutral-500">Regions</Link><Link href="/settings" className="py-2 hover:text-neutral-500">Settings</Link></nav></aside></div></main>
}
