import Link from 'next/link'
import { ArrowRight, BookOpen, Camera, MapPinned, ShieldCheck, Users, ShoppingBag } from 'lucide-react'

const stories=[['A maker’s morning in Bo','People','A short visual story about the hands, place and practice behind a local craft.'],['From farm note to buyer brief','Trade','How better evidence can change the conversation between producer and international buyer.'],['Listening before listing','Community','Why local context belongs beside every product page.']]
const pillars=[
  ['Discover','Surface local products, materials, stories and regional knowledge.','/discover',ShoppingBag],
  ['Community','Contributors, makers and local researchers build the evidence trail.','/community',Users],
  ['Verify','Provenance, sources, responsible-sourcing and export readiness stay visible.','/verification',ShieldCheck],
]
export default function Ecosystem(){return <section className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="max-w-3xl"><div className="text-xs font-black uppercase tracking-[.22em] text-sky-600">SLorigins ecosystem</div><h1 className="mt-2 text-4xl font-black tracking-tight md:text-6xl">One connected system from local knowledge to global demand.</h1><p className="mt-4 leading-7 text-slate-500">SLorigins connects discovery, community evidence, verification, buyer demand and responsible sourcing instead of treating them as separate pages.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{pillars.map(([title,text,href,Icon])=><Link href={href} key={title} className="depth-card rounded-[1.7rem] border border-sky-100 bg-white p-7 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-sky-50 text-sky-600"><Icon size={22}/></div><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><div className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-sky-700">Open module <ArrowRight size={15}/></div></Link>)}</div><div className="mt-14"><div className="text-xs font-black uppercase tracking-[.22em] text-sky-600">Stories & field notes</div><h2 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">The people behind the origins.</h2><p className="mt-3 max-w-2xl text-slate-500 leading-7">Stories are not decoration here. They preserve context around products, places, makers and the choices involved in responsible sourcing.</p><div className="mt-8 grid gap-6 lg:grid-cols-3">{stories.map(([title,tag,text],i)=><Link href={`/stories/${i+1}`} key={title} className="depth-card group overflow-hidden rounded-[1.8rem] border border-sky-100 bg-white shadow-sm"><div className="aspect-[16/10] bg-gradient-to-br from-sky-100 to-white grid place-items-center text-sky-300"><Camera size={42}/></div><div className="p-6"><div className="text-[11px] font-black uppercase tracking-wider text-sky-600">{tag}</div><h3 className="mt-2 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><div className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-sky-700">Read field note <ArrowRight size={15}/></div></div></Link>)}</div></div><div className="mt-12 grid gap-4 md:grid-cols-2"><div className="depth-card rounded-[1.7rem] border border-sky-100 bg-white p-7"><BookOpen className="text-sky-600"/><h2 className="mt-4 text-2xl font-black">Field notes</h2><p className="mt-2 text-sm leading-6 text-slate-500">Long-form context on regions, materials, people and the sourcing journey.</p></div><div className="depth-card rounded-[1.7rem] border border-sky-100 bg-white p-7"><MapPinned className="text-sky-600"/><h2 className="mt-4 text-2xl font-black">Place matters</h2><p className="mt-2 text-sm leading-6 text-slate-500">Every story can be connected back to the district and community where it began.</p></div></div></section>}
