export const locales = {
  en: { name: 'English', native: 'English' },
  kri: { name: 'Krio', native: 'Krio' },
  men: { name: 'Mende', native: 'Mende' },
  tem: { name: 'Temne', native: 'Temne' },
} as const
export type Locale = keyof typeof locales
export type Copy = Record<string,string>

const en = {
  discover:'Discover',community:'Community',regions:'Regions',buyers:'Buyers',stories:'Stories',ecosystem:'Ecosystem',signIn:'Sign in',home:'Home',profile:'Profile',settings:'Settings',notifications:'Notifications',submit:'Submit a discovery',language:'Language',join:'Join the community',explore:'Explore',about:'About',howItWorks:'How it works',verification:'Verification',legal:'Legal & sustainability',createPost:'Create post',latest:'Latest from the community',browseAll:'Browse all',welcome:'Welcome back',communityHome:'Community home',whatYouDo:'What you do',region:'Region',district:'District',chiefdom:'Chiefdom / town',country:'Country',fullName:'Full name',email:'Email',password:'Password',continue:'Continue',back:'Back',createAccount:'Create account',account:'Account',yourPlace:'Your place',aboutYou:'About you',profilePhoto:'Profile photo',openHome:'Open community home',save:'Save',loading:'Please wait…',publish:'Publish post',writeSomething:'Write something…',image:'Image',text:'Text',details:'Details',destination:'Destination',quantity:'Quantity',createRequest:'Create a buyer request',submitRequest:'Submit request',noPosts:'No posts yet. Be the first to share a note, image or discovery.',languageSaved:'Language preference saved.'
}

export const translations: Record<Locale, Copy> = {
  en,
  kri:{...en,discover:'Diskovah',community:'Kɔmyuniti',regions:'Plis dɛm',buyers:'Buya dɛm',stories:'Stori dɛm',ecosystem:'Ekosistem',signIn:'Sain in',home:'Os',profile:'Profil',settings:'Set am',notifications:'Notifikeshɔn',submit:'Send discovery',language:'Langwej',join:'Join di kɔmyuniti',explore:'Luk',about:'Abaot',howItWorks:'Aw e wok',verification:'Verifikeshɔn',legal:'Lɔ & wetin na right',createPost:'Mek post',latest:'Di latest na di kɔmyuniti',browseAll:'Luk all',welcome:'Yu don kam bak',communityHome:'Kɔmyuniti os',whatYouDo:'Wetina yu de wok',region:'Region',district:'District',chiefdom:'Chiefdom / taun',country:'Kontin',fullName:'Ful nem',email:'Email',password:'Paswɔd',continue:'Go ahead',back:'Bak',createAccount:'Mek akawnt',account:'Akawnt',yourPlace:'Yu ples',aboutYou:'Abaot yu',profilePhoto:'Foto fɔ profil',openHome:'Opɛn kɔmyuniti os',save:'Save',loading:'Wan smɔl taim…',publish:'Publish post',writeSomething:'Write wan tin…',image:'Foto',text:'Wɔd dɛm',details:'Ditayl',destination:'Destination',quantity:'Amount',createRequest:'Mek wan buya request',submitRequest:'Send request',noPosts:'Nɔ post yet. Yu fit bin di fos fɔ share wan note, foto or discovery.',languageSaved:'Yu language preference save.'},
  men:{...en,discover:'Nyehila',community:'Nɔɔ',regions:'Gbele',buyers:'Maa',stories:'Kɔi',ecosystem:'Nyehila bɛlɛ',signIn:'Pɛlɛ',home:'Kɛlɛ',profile:'Yela',settings:'Kɛlɛma',notifications:'Tɔɔma',submit:'Kɛ discovery',language:'Kumase',join:'Kɛlɛ nɔɔi',explore:'Nyehila',about:'Kɛlɛ yela',howItWorks:'Kɛlɛma wiya',verification:'Tɔɔma yɛlɛ',legal:'Lɔgɔ',createPost:'Kɛ kɔi',latest:'Kɛlɛ nɔɔi yela',browseAll:'Nɔɔi bɛlɛ',welcome:'A kɛlɛ',communityHome:'Nɔɔi kɛlɛ',whatYouDo:'Naa i kɛlɛ',region:'Gbele',district:'District',chiefdom:'Chiefdom / kɔi',country:'Hɛrɛ',fullName:'Yela bɛlɛ',email:'Email',password:'Password',continue:'Nya',back:'Kɛlɛ',createAccount:'Kɛ akawnt',account:'Akawnt',yourPlace:'I kɛlɛma',aboutYou:'I yela',profilePhoto:'Yela foto',openHome:'Kɛlɛ nɔɔi',save:'Sɛvɛ',loading:'Pɛlɛ…',publish:'Kɛ kɔi bɛlɛ',writeSomething:'Kɛ yɛlɛ…',image:'Foto',text:'Yɛlɛ',details:'Bɛlɛ',destination:'Kɛlɛma',quantity:'Kɛlɛ gɔ',createRequest:'Kɛ maa bɛlɛ',submitRequest:'Kɛlɛ bɛlɛ',noPosts:'Nɔɔi kɔi nɛ. I kɛlɛ fos fɔ kɛlɛ yɛlɛ, foto ya discovery.',languageSaved:'Kumase kɛlɛ save.'},
  tem:{...en,discover:'Ŋma',community:'Nɔŋɔi',regions:'Ŋma ŋa',buyers:'Pɛla',stories:'Mɛŋɛi',ecosystem:'Nɔŋɔiŋa',signIn:'Kɛlɛ',home:'Kɛlɛ',profile:'Ɔna',settings:'Fɛlɛ',notifications:'Tɔŋɔi',submit:'Kɛ discovery',language:'Kasa',join:'Kɛlɛ nɔŋɔi',explore:'Ŋma',about:'Ɔna yela',howItWorks:'Awuna kɛlɛ',verification:'Kɛlɛ sɔɔ',legal:'Lɔgɔ',createPost:'Kɛ mɛŋɛi',latest:'Nɔŋɔi mɛŋɛi',browseAll:'Ŋma nɔŋɔi',welcome:'Kɛlɛ ba',communityHome:'Nɔŋɔi kɛlɛ',whatYouDo:'Ŋa i kɛlɛ',region:'Ŋma',district:'District',chiefdom:'Chiefdom / taun',country:'Kɔmɔ',fullName:'Ɔna',email:'Email',password:'Password',continue:'Kɛlɛ fɔlɔ',back:'Bak',createAccount:'Kɛ akawnt',account:'Akawnt',yourPlace:'I ŋa',aboutYou:'I Ɔna',profilePhoto:'Ɔna foto',openHome:'Kɛlɛ nɔŋɔi os',save:'Sɛvɛ',loading:'Pɛlɛ…',publish:'Kɛlɛ mɛŋɛi',writeSomething:'Kɛ mɛŋɛi…',image:'Foto',text:'Yɛlɛ',details:'Bɛlɛ',destination:'Kɛlɛma',quantity:'Kɛlɛ gɔ',createRequest:'Kɛlɛ pɛla bɛlɛ',submitRequest:'Send bɛlɛ',noPosts:'Nɔŋɔi mɛŋɛi nɛ. I kɛlɛ fos.',languageSaved:'Kasa save.'}
}
